### ISSUE TITLE
Crash on Save Load

### ISSUE THREAD

**Issue by sirreality** [Alphablackwolf/SkillPrestige#1]
> [11:20:23.586 PM] SDV Version: 1.11
> [11:20:23.587 PM] SMAPI Version: 0.40.0 1.1-3
> [11:20:23.587 PM] Validating api paths...
> [11:20:23.597 PM] Initializing SDV Assembly...
> [11:20:23.598 PM] Injecting New SDV Version...
> [11:20:23.598 PM] Starting SDV...
> [11:20:23.750 PM] Patching SDV Graphics Profile...
> [11:20:23.753 PM] LOADING MODS
> [11:20:23.753 PM] Found Manifest: C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods!EntoaroxFramework\manifest.json
> [11:20:24.103 PM] Created psconfigs directory @C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods!EntoaroxFramework\psconfigs
> [11:20:24.106 PM] Loading Mod DLL...
> [11:20:24.107 PM] LOADED MOD: Entoarox Framework by Entoarox - Version StardewModdingAPI.Version | Description: A framework to make stardew modding easier! (@ C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods!EntoaroxFramework\EntoaroxFramework.dll)
> [11:20:24.132 PM] Found Manifest: C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\AdvancedLocationLoader\manifest.json
> [11:20:24.155 PM] Created psconfigs directory @C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\AdvancedLocationLoader\psconfigs
> [11:20:24.158 PM] Loading Mod DLL...
> [11:20:24.158 PM] LOADED MOD: Advanced Location Loader by Entoarox - Version StardewModdingAPI.Version | Description: Get your content into stardew without replacing any xnb files. (@ C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\AdvancedLocationLoader\AdvancedLocationLoader.dll)
> [11:20:24.172 PM] Registered command: notify_ALLFinished
> [11:20:24.460 PM] Found Manifest: C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\EventNotifications\manifest.json
> [11:20:24.478 PM] Created psconfigs directory @C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\EventNotifications\psconfigs
> [11:20:24.481 PM] LOADED MOD: Event Notifications by Ryuuze & Dreamsicl - Version StardewModdingAPI.Version | Description: Notifies you of any events on the current day. (@ C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\EventNotifications\EventNotifications.dll)
> [11:20:24.480 PM] Loading Mod DLL...
> [11:20:24.512 PM] Found Manifest: C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\FarmAutomation.BarnDoorAutomation\manifest.json
> [11:20:24.532 PM] Created psconfigs directory @C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\FarmAutomation.BarnDoorAutomation\psconfigs
> [11:20:24.536 PM] Loading Mod DLL...
> [11:20:24.536 PM] [INFO] Initalizing BarnDoorAutomationMod
> [11:20:24.537 PM] [INFO] Loading configuration for BarnDoorAutomationConfiguration
> [11:20:24.542 PM] LOADED MOD: FarmAutomation Mod: Barn Door Automation by Oranisagu - Version StardewModdingAPI.Version | Description: Automatically opens and closes animal doors at set times (@ C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\FarmAutomation.BarnDoorAutomation\FarmAutomation.BarnDoorAutomation.dll)
> [11:20:24.543 PM] Found Manifest: C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\FarmAutomation.ItemCollector\manifest.json
> [11:20:24.567 PM] Created psconfigs directory @C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\FarmAutomation.ItemCollector\psconfigs
> [11:20:24.569 PM] Loading Mod DLL...
> [11:20:24.571 PM] [INFO] Initalizing ItemCollectorMod
> [11:20:24.571 PM] [INFO] Loading configuration for ItemCollectorConfiguration
> [11:20:24.582 PM] LOADED MOD: FarmAutomation Mod: Item Collector by Oranisagu - Version StardewModdingAPI.Version | Description: Collects items from animals and machines and refills machines if a nearby chest has the necessary raw materials. (@ C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\FarmAutomation.ItemCollector\FarmAutomation.ItemCollector.dll)
> [11:20:24.584 PM] Found Manifest: C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\FasterPaths\manifest.json
> [11:20:24.606 PM] Created psconfigs directory @C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\FasterPaths\psconfigs
> [11:20:24.607 PM] Loading Mod DLL...
> [11:20:24.608 PM] LOADED MOD: Faster Paths by Entoarox - Version StardewModdingAPI.Version | Description: Makes your farmer move faster while on paths (@ C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\FasterPaths\FasterPaths.dll)
> [11:20:24.623 PM] Registered command: fp_info
> [11:20:24.623 PM] Found Manifest: C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\HarvestWithScytheSMAPI\manifest.json
> [11:20:24.640 PM] Created psconfigs directory @C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\HarvestWithScytheSMAPI\psconfigs
> [11:20:24.644 PM] Loading Mod DLL...
> [11:20:24.644 PM] LOADED MOD: HarvestWithScytheSMAPI by ThatNorthernMonkey - Version StardewModdingAPI.Version | Description:  (@ C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\HarvestWithScytheSMAPI\HarvestWithScytheSMAPI.dll)
> [11:20:24.647 PM] Found Manifest: C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\InstantGeode\manifest.json
> [11:20:24.667 PM] Created psconfigs directory @C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\InstantGeode\psconfigs
> [11:20:24.671 PM] Loading Mod DLL...
> [11:20:24.678 PM] LOADED MOD: InstantGeode by Basicallymeatthispoint - Version StardewModdingAPI.Version | Description: Instant Geodes (@ C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\InstantGeode\InstantGeode.dll)
> [11:20:24.681 PM] Found Manifest: C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\JJB\manifest.json
> [11:20:24.709 PM] Created psconfigs directory @C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\JJB\psconfigs
> [11:20:24.712 PM] Loading Mod DLL...
> [11:20:24.713 PM] LOADED MOD: Jiggly Junimo Bundles by Jonas Henriksson - Version StardewModdingAPI.Version | Description: Shows needed ingredients for a bundle, and jiggles bundles if you have a depositable item. (@ C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\JJB\JJB.dll)
> [11:20:24.715 PM] Found Manifest: C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\JunimoDepositAnywhere\manifest.json
> [11:20:24.732 PM] Created psconfigs directory @C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\JunimoDepositAnywhere\psconfigs
> [11:20:24.734 PM] Loading Mod DLL...
> [11:20:24.735 PM] Found Manifest: C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\LookupAnything\manifest.json
> [11:20:24.734 PM] LOADED MOD: Junimo Deposit Anywhere by Zoryn - Version StardewModdingAPI.Version | Description: Allows you to deposit items into budles from anywhere (@ C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\JunimoDepositAnywhere\JunimoDepositAnywhere.dll)
> [11:20:24.734 PM] [INFO] JunimoDepositAnywhere by Zoryn => Initialized (Press F5 To Reload Config)
> [11:20:24.754 PM] Created psconfigs directory @C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\LookupAnything\psconfigs
> [11:20:24.765 PM] Loading Mod DLL...
> [11:20:24.766 PM] LOADED MOD: LookupAnything by Pathoschild - Version StardewModdingAPI.Version | Description: View metadata about anything by pressing a button. [version 1.4](@ C:Program Files %28x86%29SteamsteamappscommonStardew ValleyModsLookupAnythingLookupAnything.dll)
> [11:20:24.831 PM] Found Manifest: C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\M007_ExtendedFridge\manifest.json
> [11:20:24.851 PM] Created psconfigs directory @C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\M007_ExtendedFridge\psconfigs
> [11:20:24.854 PM] Loading Mod DLL...
> [11:20:24.854 PM] LOADED MOD: Extended Fridge by Crystalmir - Version StardewModdingAPI.Version | Description: Extended Fridges alpha (@ C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\M007_ExtendedFridge\M007_ExtendedFridge.dll)
> [11:20:24.877 PM] Found Manifest: C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\Museum_Rearranger\manifest.json
> [11:20:24.898 PM] Created psconfigs directory @C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\Museum_Rearranger\psconfigs
> [11:20:24.899 PM] Loading Mod DLL...
> [11:20:24.900 PM] LOADED MOD: Museum Rearranger by Omegasis - Version StardewModdingAPI.Version | Description: Allows the user to rearrange the Museum without the need for something to donate. (@ C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\Museum_Rearranger\Museum_Rearranger.dll)
> [11:20:24.900 PM] Found Manifest: C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\NPCMapLocations\manifest.json
> [11:20:24.921 PM] Created psconfigs directory @C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\NPCMapLocations\psconfigs
> [11:20:24.923 PM] Loading Mod DLL...
> [11:20:24.924 PM] LOADED MOD: NPC Map Locations Mod by Bouhm - Version StardewModdingAPI.Version | Description: Shows NPC locations on the map (@ C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\NPCMapLocations\NPCMapLocations.dll)
> [11:20:24.983 PM] Found Manifest: C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\SkillPrestige\manifest.json
> [11:20:25.002 PM] Created psconfigs directory @C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\SkillPrestige\psconfigs
> [11:20:25.008 PM] Loading Mod DLL...
> [11:20:25.009 PM] LOADED MOD: Skill Prestige by Alphablackwolf - Version StardewModdingAPI.Version | Description:  (@ C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\SkillPrestige\SkillPrestige.dll)
> [11:20:25.010 PM] Skill Prestige Mod: options file path: C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\SkillPrestige\config.json
> [11:20:25.010 PM] Skill Prestige Mod: Deserializing options file...
> [11:20:25.116 PM] Skill Prestige Mod version 1.0.2.5 by Alphablackwolf Initialized.
> [11:20:25.150 PM] Found Manifest: C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\SkipIntro\manifest.json
> [11:20:25.168 PM] Created psconfigs directory @C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\SkipIntro\psconfigs
> [11:20:25.170 PM] LOADED MOD: SkipIntro by Pathoschild - Version StardewModdingAPI.Version | Description: Skips the game's loading intro. (@ C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\SkipIntro\Pathoschild.StardewValley.SkipIntro.dll)
> [11:20:25.171 PM] Found Manifest: C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\SMAPIChestLabelSystem\manifest.json
> [11:20:25.169 PM] Loading Mod DLL...
> [11:20:25.189 PM] Created psconfigs directory @C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\SMAPIChestLabelSystem\psconfigs
> [11:20:25.192 PM] Loading Mod DLL...
> [11:20:25.192 PM] LOADED MOD: Chest Label System by Maurício Gomes (Speeder) - Version StardewModdingAPI.Version | Description: Allow players to label their chests. (@ C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\SMAPIChestLabelSystem\SMAPIChestLabelSystem.dll)
> [11:20:25.193 PM] Found Manifest: C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\SMAPIHealthBarMod\manifest.json
> [11:20:25.217 PM] Created psconfigs directory @C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\SMAPIHealthBarMod\psconfigs
> [11:20:25.219 PM] Loading Mod DLL...
> [11:20:25.219 PM] LOADED MOD: Health Bars Mod by Maurício Gomes (Speeder) - Version StardewModdingAPI.Version | Description: Add health bars to monsters. (@ C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\SMAPIHealthBarMod\SMAPIHealthBarMod.dll)
> [11:20:25.227 PM] Found Manifest: C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\StardewCJB\manifest.json
> [11:20:25.246 PM] Created psconfigs directory @C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\StardewCJB\psconfigs
> [11:20:25.249 PM] LOADED 19 MODS
> [11:20:25.250 PM] SDV Loaded Into Memory
> [11:20:25.249 PM] LOADED MOD: CJB Show Item Sell Price by CJ Bok - Version StardewModdingAPI.Version | Description: Show item sell price in your inventory! (@ C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods\StardewCJB\StardewCJB.dll)
> [11:20:25.252 PM] Applying Final SDV Tweaks...
> [11:20:25.248 PM] Loading Mod DLL...
> [11:20:25.250 PM] Initializing Console Input Thread...
> [11:20:25.251 PM] Registered command: help
> [11:20:25.455 PM] XNA Initialize
> [11:20:25.458 PM] XNA LoadContent
> [11:20:25.725 PM] Initializing Debug Assets...
> [11:20:33.884 PM] Game Loaded
> [11:20:43.258 PM] Skill Prestige Mod: Error while attempting to create a per save options file. 
>  System.ArgumentException: Empty path name is not legal.
>    at System.IO.File.WriteAllLines(String path, String[] contents)
>    at SkillPrestige.PerSaveOptions.Save()
>    at SkillPrestige.PerSaveOptions.SetupPerSaveOptionsFile() 
>  Please file a bug report on NexusMods.
> [11:20:43.258 PM] Skill Prestige Mod: Error while attempting to create a per save options file. 
>  System.ArgumentException: Empty path name is not legal.
>    at System.IO.File.WriteAllLines(String path, String[] contents)
>    at SkillPrestige.PerSaveOptions.Save()
>    at SkillPrestige.PerSaveOptions.SetupPerSaveOptionsFile()
>    at SkillPrestige.PerSaveOptions.LoadPerSaveOptions()
>    at SkillPrestige.PerSaveOptions.get_Instance()
>    at SkillPrestige.PerSaveOptions.SetupPerSaveOptionsFile() 
>  Please file a bug report on NexusMods.

**Comment by Alphablackwolf** [comment]
I released a new version that has a backup method, if you get latest and try again, let me know if it works or not.

**Comment by sirreality** [comment]
Got the latest, it works, still getting a similar error log, but am able to use mouse to prestige my farming skill (only one at 10 in current file), and assign the point.  Yay!  Log attached for completeness.

[MODDED_ProgramLog.Log_LATEST.txt](https://github.com/Alphablackwolf/SkillPrestige/files/520726/MODDED_ProgramLog.Log_LATEST.txt)

**Comment by Alphablackwolf** [comment]
Awesome, thank you for the data and the help!
